### ISSUE TITLE
ChunkedEncodingError

### ISSUE THREAD

**Issue by keyz182** [ryanmcgrath/twython#288]
Just spotted the following in the logs for a pair of my streamers:

``` python
Traceback (most recent call last):
  File "/home/keyz/tweets/tweetstream.py", line 20, in <module>
    stream.statuses.filter(locations=location)
  File "/usr/local/lib/python2.7/dist-packages/twython/streaming/types.py", line 65, in filter
    self.streamer._request(url, 'POST', params=params)
  File "/usr/local/lib/python2.7/dist-packages/twython/streaming/api.py", line 134, in _request
    for line in response.iter_lines(self.chunk_size):
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 602, in iter_lines
    decode_unicode=decode_unicode):
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 575, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: IncompleteRead(0 bytes read)
```

The line in question is

``` python
for line in response.iter_lines(self.chunk_size)
```

in https://github.com/ryanmcgrath/twython/blob/master/twython/streaming/api.py

Should there be some catch for this to pass it to on_error, rather than throwing an uncaught exception?

Looks like the exception is a fairly new one, see https://github.com/kennethreitz/requests/pull/1498.

I'd submit a patch, but I'm not sure of the best way to catch this. Putting a try block around the whole loop seems messy.

**Comment by stevenzim** [comment]
@colditzjb  Thanks a bunch for the workaround.  The try/except with while solution is brilliantly simple.  I am collecting many 1000s of tweets an hour and it drops every hour or so.  Now I can sleep better.

**Comment by andrewtatham** [comment]
I get this error every few hours or so, with python 3.4 running 8 streams in different threads, on a raspberry pi 2. Firmware and packages updated to latest versions. I can supply more info if required. In the meantime I have a similar try/catch workaround in place.

[full code here](https://github.com/andrewtatham/twitterpibot)

``Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 529, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.4/http/client.py", line 621, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/usr/lib/python3.4/http/client.py", line 680, in _safe_readinto
    raise IncompleteRead(bytes(mvb[0:total_bytes]), len(b))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 1 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 214, in read
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 1 more expected)', IncompleteRead(0 bytes read, 1 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/twitterpibot/twitterpibot/tasks/__init__.py", line 35, in _run_wrapper
    task.on_run()
  File "/home/pi/twitterpibot/twitterpibot/tasks/StreamTweetsTask.py", line 26, in on_run
    self._streamer.user()
  File "/usr/local/lib/python3.4/dist-packages/twython/streaming/types.py", line 31, in user
    self.streamer._request(url, params=params)
  File "/usr/local/lib/python3.4/dist-packages/twython/streaming/api.py", line 141, in _request
    for line in response.iter_lines(self.chunk_size):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 693, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 656, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read, 1 more expected)', IncompleteRead(0 bytes read, 1 more expected))``

**Comment by philostow** [comment]
I resolved this issue on my python 2.7 environment by upgrading requests to 2.12.1.  requests-toolbelt was already at 0.7.0

**Comment by gordonmangum** [comment]
Like @philostow, this issue plagued me for quite a while (it was happening for me every 3-5 days), but upgrading requests in python 2.7 resolved it.

**Comment by lxd235** [comment]
hi,all.I can reproduce steadily.i use django+uwsgi+nginx and use requset lib , send a post requset.if the session is expire, the bug is found. i catch network traffic by whershark,found there is no respone http.
so, i serach this ,found ,this is because django found session expire, it will return 403 without consume the body,it will cause uwsgi and nginx error.so if you post data,you must consume it in your app.

and, i will add decorator, reset the session when is expire.
