### ISSUE TITLE
TwythonStreamer: Connection reset due to socket.error 

### ISSUE THREAD

**Issue by jukkahuhtamaki** [ryanmcgrath/twython#311]
My TwythonStreamer-based application was stopped due to a socket.error. Traceback follows: 

Traceback (most recent call last):
  File "run.twythonstreamer.py", line 63, in <module>
    stream.statuses.filter(track='example,another')
  File "/home/ec2-user/2014/Environments/twanalytics/lib/python2.6/site-packages/twython/streaming/types.py", line 65, in filter
    self.streamer._request(url, 'POST', params=params)
  File "/home/ec2-user/2014/Environments/twanalytics/lib/python2.6/site-packages/twython/streaming/api.py", line 134, in _request
    for line in response.iter_lines(self.chunk_size):
  File "/home/ec2-user/2014/Environments/twanalytics/lib/python2.6/site-packages/requests/models.py", line 648, in iter_lines
    decode_unicode=decode_unicode):
  File "/home/ec2-user/2014/Environments/twanalytics/lib/python2.6/site-packages/requests/models.py", line 616, in generate
    decode_content=True):
  File "/home/ec2-user/2014/Environments/twanalytics/lib/python2.6/site-packages/requests/packages/urllib3/response.py", line 236, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/ec2-user/2014/Environments/twanalytics/lib/python2.6/site-packages/requests/packages/urllib3/response.py", line 183, in read
    data = self._fp.read(amt)
  File "/usr/lib64/python2.6/httplib.py", line 528, in read
    return self._read_chunked(amt)
  File "/usr/lib64/python2.6/httplib.py", line 561, in _read_chunked
    line = self.fp.readline()
  File "/usr/lib64/python2.6/socket.py", line 433, in readline
    data = recv(1)
  File "/usr/lib64/python2.6/ssl.py", line 215, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.6/ssl.py", line 136, in read
    return self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer2014-02-28T12:43:14.989203 1263200

**Comment by jukkahuhtamaki** [comment]
@michaelhelmick I have totally missed your post, sorry about that. I was struggling to keep the streamer running - perhaps server time was causing issues all along. Is the issue and the fix that you mention still relevant?

**Comment by michaelhelmick** [comment]
@jukkahuhtamaki Try running `ntpd -q` on the server.
