### ISSUE TITLE
Twython cursor with get_mentions_timeline, multiple issues

### ISSUE THREAD

**Issue by chasrmartin** [ryanmcgrath/twython#361]
- Each iteration on a cursor on get_mentions_timeline makes a new twitter API call.
- Each iteration returns the same (first) element in the list returned by `get_mentions_timeline`.

Setup: Create a cursor on get_mentions_timeline:

```
print "Results:\n"
results = twitter.cursor(
    twitter.get_mentions_timeline
    , count=200
    , include_entities=True
    , include_rts=1
)
```

Test: iterate on the results

```
count = 0
a_result = {}

for result in results:
    if len(set(result) ^ set(a_result)) == 0:
        print "Same result returned."
    a_result = result
```

Result:

```
 $ python timeline_cursor_bug.py 
Twitter initialized
<type 'dict'>
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Lenth of return: 23
<type 'dict'>
Same result returned.
Lenth of return: 23
<type 'dict'>
Same result returned.
Lenth of return: 23
<type 'dict'>
Same result returned.
Lenth of return: 23
<type 'dict'>
Same result returned.
Lenth of return: 23
<type 'dict'>
Same result returned.
Lenth of return: 23
<type 'dict'>
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
<type 'dict'>
Same result returned.
Lenth of return: 22
Traceback (most recent call last):
  File "timeline_cursor_bug.py", line 71, in <module>
    for result in results:
  File "/Users/sumazi/.virtualenvs/tweeting/lib/python2.7/site-packages/twython/api.py", line 477, in cursor
    content = function(**params)
  File "/Users/sumazi/.virtualenvs/tweeting/lib/python2.7/site-packages/twython/endpoints.py", line 32, in get_mentions_timeline
    return self.get('statuses/mentions_timeline', params=params)
  File "/Users/sumazi/.virtualenvs/tweeting/lib/python2.7/site-packages/twython/api.py", line 263, in get
    return self.request(endpoint, params=params, version=version)
  File "/Users/sumazi/.virtualenvs/tweeting/lib/python2.7/site-packages/twython/api.py", line 257, in request
    api_call=url)
  File "/Users/sumazi/.virtualenvs/tweeting/lib/python2.7/site-packages/twython/api.py", line 198, in _request
    retry_after=response.headers.get('X-Rate-Limit-Reset'))
twython.exceptions.TwythonRateLimitError: Twitter API returned a 429 (Too Many Requests), Rate limit exceeded
```

**Comment by michaelhelmick** [comment]
I think it has to make a new Twitter API request. As for the same results, please refer to my comment in your other issue and let me know if using the code from PR #386 works
