### ISSUE TITLE
Streaming example is not working, at least on my systems

### ISSUE THREAD

**Issue by debunge** [ryanmcgrath/twython#374]
Pythons 2.7.8, 2.7.6. 
twython 3.2 in both cases, amazon ubuntu 14.04 and 14.10 (mint distribution). 

Trying to run example https://github.com/ryanmcgrath/twython/blob/master/examples/stream.py . The only difference is hardcoded keys:

```
from twython import TwythonStreamer

APP_KEY=     'xxxxxxxxx',
APP_SECRET =  'xxxxxxxx'
OAUTH_TOKEN = 'xxxxxxx'
OAUTH_TOKEN_SECRET =  'xxxxxxxxx'

class MyStreamer(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            print data['text'].encode('utf-8')

    def on_error(self, status_code, data):
        print status_code, data

stream = MyStreamer(APP_KEY, APP_SECRET,
                    OAUTH_TOKEN, OAUTH_TOKEN_SECRET)

stream.statuses.filter(track='twitter')
```

python stream.py 

```
Traceback (most recent call last):
  File "stream.py", line 19, in <module>
    stream.statuses.filter(track=u'twitter')
  File "/usr/local/lib/python2.7/dist-packages/twython/streaming/types.py", line 65, in filter
    self.streamer._request(url, 'POST', params=params)
  File "/usr/local/lib/python2.7/dist-packages/twython/streaming/api.py", line 139, in _request
    response = _send(retry_counter)
  File "/usr/local/lib/python2.7/dist-packages/twython/streaming/api.py", line 123, in _send
    response = func(url, **requests_args)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 450, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 381, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 308, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 495, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth1_auth.py", line 79, in __call__
    unicode(r.url), unicode(r.method), r.body or '', r.headers)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/__init__.py", line 304, in sign
    ('oauth_signature', self.get_oauth_signature(request)))
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/__init__.py", line 131, in get_oauth_signature
    uri, headers, body = self._render(request)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/__init__.py", line 203, in _render
    request.oauth_params, request.headers, realm=realm)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/utils.py", line 31, in wrapper
    return target(params, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/parameters.py", line 57, in prepare_headers
    escaped_value = utils.escape(value)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/utils.py", line 56, in escape
    'Got %s of type %s.' % (u, type(u)))
ValueError: Only unicode objects are escapable. Got <generator object <genexpr> at 0x7fd788c86cd0> of type <type 'generator'>
```

Surprisingly, 

```
streamer = TweetStreamer(consumer_key, consumer_secret,
                         access_token, access_token_secret)

users = [27226503, 1963312058, 594026078, 19224439, 23125257, 1534167900, 17006157, 116763916, 148529707, 36047098, 159904799, 872052960, 348345136, 241709263, 1364930179, 304909941, 397489668, 1305556297, 217284148, 1425781254]

papers = [18856867, 18858395, 5988062, 71567590, 46671396, 151106990, 15905103, 4898091, 26574283, 16184358]

users = users + papers

streamer.statuses.filter(follow = users)
```

works just fine.

**Comment by michaelhelmick** [comment]
Hm, can you let us know which version of Twython you're using?
