### ISSUE TITLE
twython.exceptions.TwythonError: Twitter API returned a 404 (Not Found), Sorry, that page does not exist.

### ISSUE THREAD

**Issue by computersarecool** [ryanmcgrath/twython#379]
```
from twython import Twython
import json

APP_KEY = 'xxx'
APP_SECRET = 'yay'
twitter = Twython(APP_KEY, APP_SECRET, 'zzz', 'www')

results = twitter.cursor(twitter.get_user_timeline, screen_name="jeremy_olander", count=200)
for i in results:
    print(i)
    break
```

returns:
`twython.exceptions.TwythonError: Twitter API returned a 404 (Not Found), Sorry, that page does not exist.`

In Python 3.3

**Comment by sinistersnare** [comment]
I am getting the same error. The equivalent method works in the twitter API sandbox.

**Comment by michaelhelmick** [comment]
@computersarecool I redacted your keys and secrets so others can't use them. Please *_don't_* post that type of _personal_ info in public forums.

Is there anyway you can print the full stack trace and not _just_ the exception? Thanks!

**Comment by herrBez** [comment]
I get a very similar error in the show user API with a no-more existing account. 
Altough I surrounded my call to the twython API:
```python
try:
    result = twython_instance.show_user(
        timeout=120,  # Max Timeout 2 minutes
        **params
    )

except TwythonRateLimitError as tre:
    # Code to pause until the reaching of the next release time
except TwythonError as te:
    # Code to threat the generic twython exception without exiting
```
**I get a TwythonError, that exits the program**

The complete traceback is the following (I'm running python3.6 with twython==3.6.0)
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/twython/endpoints.py", line 569, in show_user
    return self.get('users/show', params=params)
  File "/usr/local/lib/python3.6/dist-packages/twython/api.py", line 264, in get
    return self.request(endpoint, params=params, version=version)
  File "/usr/local/lib/python3.6/dist-packages/twython/api.py", line 258, in request
    api_call=url)
  File "/usr/local/lib/python3.6/dist-packages/twython/api.py", line 194, in _request
    retry_after=response.headers.get('X-Rate-Limit-Reset'))
twython.exceptions.TwythonError: Twitter API returned a 404 (Not Found), User not found.
```

The problem seems to occur in the instantiation of the exception itself.
