### ISSUE TITLE
Error on Sample Stream

### ISSUE THREAD

**Issue by abdullah2993** [ryanmcgrath/twython#393]
Sample stream throws error after a while
**Code:**

``` python
from twython import TwythonStreamer


class GetStream(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            print(data['text'].encode('utf-8'))

    def on_error(self, status_code, data):
        print("Error: ", status_code, data)

stream = GetStream(APP_KEY, APP_SECRET,OAUTH_TOKEN, OAUTH_TOKEN_SECRET)

stream.statuses.sample()
```

**Error:**

```

Traceback (most recent call last):
  File "C:/Users/Abdullah/PycharmProjects/Tnalysis/Main.py", line 17, in <module>
    stream.statuses.sample()
  File "C:\Python34\lib\site-packages\twython\streaming\types.py", line 78, in sample
    self.streamer._request(url, params=params)
  File "C:\Python34\lib\site-packages\twython\streaming\api.py", line 141, in _request
    for line in response.iter_lines(self.chunk_size):
  File "C:\Python34\lib\site-packages\requests\models.py", line 715, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "C:\Python34\lib\site-packages\requests\models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\response.py", line 450, in read_chunked
    chunk = self._handle_chunk(amt)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\response.py", line 411, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "C:\Python34\lib\http\client.py", line 664, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(0 bytes read, 1 more expected)
```

**Comment by michaelhelmick** [comment]
Hi, do you know how long it takes for this `IncompleteRead`to be thrown? "A while" is ambiguous.

**Comment by LynnCo** [comment]
Got this same issue, happened after about 30 seconds

**Comment by Zedsquared** [comment]
Same here, occurs every minute or so, seems harmless but requires catching.
