### ISSUE TITLE
upload file with post params

### ISSUE THREAD

**Issue by AlexMercier** [ryanmcgrath/twython#400]
i try to post file but get error

```
Traceback (most recent call last):
  <...skip some trace trace...>telegram_bot.py", line 18, in sendMessage
    r = requests.post(url,  data=files, params=params, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 608, in send
    r.content
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 660, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

```

my code:
```python
		url = 'https://api.telegram.org/bot'+self.token+'/sendPhoto' #'/sendmessage'
		print('request to '+url+' with params '+chat_id+' ' + text)		
		
		headers = {'Content-Type': 'multipart/form-data'}
		
		files = {'photo': open('file.jpg', 'rb')}
		params = {'chat_id': chat_id, 'caption': 'test'}
		r = requests.post(url,  data=files, params=params, headers=headers)
		print(r.text)
```

**Comment by AlexMercier** [comment]
oh sorry, I have code error need variable name 'files' instead of 'data'
