### ISSUE TITLE
TwythonError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded

### ISSUE THREAD

**Issue by bitnumus** [ryanmcgrath/twython#404]
full trace:

2015-11-03 20:58:35,912 urllib3.connectionpool [DEBUG] :: Setting read timeout to None
Traceback (most recent call last):
  File "file", line 29, in <module>
    twitter.update_status_with_media(media=photo, status=status)
  File "file", line 130, in update_status_with_media
    return self.post('statuses/update_with_media', params=params)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 269, in post
    return self.request(endpoint, 'POST', params=params, version=version)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 259, in request
    api_call=url)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 165, in _request
    raise TwythonError(str(e))
twython.exceptions.TwythonError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/update_
with_media.json (Caused by <class 'socket.error'>: [Errno 110] Connection timed out)

Code thats using the twython function:

http://pastebin.com/aPnrSdVy

**Comment by michaelhelmick** [comment]
You're sending too many requests from the same IP address, causing api.twitter.com to refuse the connection. There really isn't much you can do except try in a few minutes after the error.

**Comment by bitnumus** [comment]
No, i'm not.

I'm sending one request per 4 hours. If i catch this error and retry 5seconds later it works just fine..

**Comment by michaelhelmick** [comment]
@bitnumus didn't mean to close this, sorry! And I don't see you making too many requests. Is the error still occurring?

I could be twitter acting up?

I just tested this and had no issues :(

**Comment by bitnumus** [comment]
No its happening every time, at the moment i'm catching the error and retrying, it succeeds on retry. As a guess could it be related to keepalive?

2015-11-09 05:46:34,955 urllib3.connectionpool [DEBUG] :: Setting read timeout to None
2015-11-09 05:46:35,261 urllib3.connectionpool [DEBUG] :: "POST /1.1/media/upload.json HTTP/1.1" 200 143
2015-11-09 05:46:35,265 urllib3.connectionpool [INFO] :: Resetting dropped connection: api.twitter.com
2015-11-09 05:46:35,585 urllib3.connectionpool [DEBUG] :: Setting read timeout to None
2015-11-09 05:46:36,007 urllib3.connectionpool [DEBUG] :: "POST /1.1/statuses/update.json HTTP/1.1" 200 1162
2015-11-09 09:46:36,115 urllib3.connectionpool [INFO] :: Resetting dropped connection: upload.twitter.com
2015-11-09 09:46:36,471 urllib3.connectionpool [DEBUG] :: Setting read timeout to None
2015-11-09 09:46:36,730 urllib3.connectionpool [DEBUG] :: "POST /1.1/media/upload.json HTTP/1.1" 200 143
2015-11-09 09:46:36,734 urllib3.connectionpool [DEBUG] :: Setting read timeout to None
2015-11-09 10:03:14,672 twitter_daemon [ERROR] :: twitter call failed
Traceback (most recent call last):
  File "", line 36, in <module>
    twitter.update_status(status=status, media_ids=[response['media_id']])
  File "/usr/local/lib/python2.7/dist-packages/twython/endpoints.py", line 107, in update_status
    return self.post('statuses/update', params=params)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 269, in post
    return self.request(endpoint, 'POST', params=params, version=version)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 259, in request
    api_call=url)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 165, in _request
    raise TwythonError(str(e))
TwythonError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/update.json (Caused by <class 'socket.error'>: [Errno 110] Connection timed out)
2015-11-09 10:03:29,700 urllib3.connectionpool [INFO] :: Resetting dropped connection: upload.twitter.com
2015-11-09 10:03:30,046 urllib3.connectionpool [DEBUG] :: Setting read timeout to None
2015-11-09 10:03:30,490 urllib3.connectionpool [DEBUG] :: "POST /1.1/media/upload.json HTTP/1.1" 200 142
2015-11-09 10:03:30,501 urllib3.connectionpool [INFO] :: Starting new HTTPS connection (8): api.twitter.com
2015-11-09 10:03:30,831 urllib3.connectionpool [DEBUG] :: Setting read timeout to None
2015-11-09 10:03:31,186 urllib3.connectionpool [DEBUG] :: "POST /1.1/statuses/update.json HTTP/1.1" 200 1161
2015-11-09 14:03:31,290 urllib3.connectionpool [INFO] :: Resetting dropped connection: upload.twitter.com
2015-11-09 14:03:31,639 urllib3.connectionpool [DEBUG] :: Setting read timeout to None
2015-11-09 14:03:31,894 urllib3.connectionpool [DEBUG] :: "POST /1.1/media/upload.json HTTP/1.1" 200 143
2015-11-09 14:03:31,897 urllib3.connectionpool [INFO] :: Resetting dropped connection: api.twitter.com
2015-11-09 14:03:32,227 urllib3.connectionpool [DEBUG] :: Setting read timeout to None
2015-11-09 14:03:32,698 urllib3.connectionpool [DEBUG] :: "POST /1.1/statuses/update.json HTTP/1.1" 200 1161

**Comment by vionemc** [comment]
I also got this error if I run twython request from APScheduler. @bitnumus do you also use any scheduler or run twython in a thread?

**Comment by prestia** [comment]
Any resolution here? I'm getting a similar error:

`twython.exceptions.TwythonError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/update_with_media.json (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)`

I shouldn't be making too many requests--one request every 6 hours from a cron job. I've been running this code without issue for several years and it started acting up about a month ago.

**Comment by navchandar** [comment]
I just ran Twython for the first time and got this error.
