### ISSUE TITLE
UnicodeDecodeError when trying to upload jpg image

### ISSUE THREAD

**Issue by SoulSkin** [ryanmcgrath/twython#409]
When attempting to upload the [following image](http://puu.sh/nrrh9.jpg), I received this error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "<my python file>", line 14
> , in tweetPhoto
>     response = twitter.upload_media(media=photo)
>   File "C:\Python27\lib\site-packages\twython\endpoints.py", line 140, in upload
> _media
>     return self.post('https://upload.twitter.com/1.1/media/upload.json', params=
> params)
>   File "C:\Python27\lib\site-packages\twython\api.py", line 269, in post
>     return self.request(endpoint, 'POST', params=params, version=version)
>   File "C:\Python27\lib\site-packages\twython\api.py", line 259, in request
>     api_call=url)
>   File "C:\Python27\lib\site-packages\twython\api.py", line 163, in _request
>     response = func(url, *_requests_args)
>   File "C:\Python27\lib\site-packages\requests\sessions.py", line 511, in post
>     return self.request('POST', url, data=data, json=json, *_kwargs)
>   File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in reques
> t
>     resp = self.send(prep, *_send_kwargs)
>   File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
>     r = adapter.send(request, *_kwargs)
>   File "C:\Python27\lib\site-packages\requests\adapters.py", line 370, in send
>     timeout=timeout
>   File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.p
> y", line 559, in urlopen
>     body=body, headers=headers)
>   File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.p
> y", line 353, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "C:\Python27\lib\httplib.py", line 1057, in request
>     self._send_request(method, url, body, headers)
>   File "C:\Python27\lib\httplib.py", line 1097, in _send_request
>     self.endheaders(body)
>   File "C:\Python27\lib\httplib.py", line 1053, in endheaders
>     self._send_output(message_body)
>   File "C:\Python27\lib\httplib.py", line 895, in _send_output
>     msg += message_body
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 109: ordina
> l not in range(128)

I used this code:
`def tweetPhoto(file):`
    `text = "testing"`
    `photo = open(file, 'rb')`
    `response = twitter.upload_media(media=photo)`
    `twitter.update_status(status=text, media_ids=[response['media_id']])`

**Comment by michaelhelmick** [comment]
Can you post the photo you're trying to send? I'm not sure if I can replicate it since I don't have a Windows machine, but I'll try my best.

**Comment by michaelhelmick** [comment]
I'm going to ping one last time before I close it. 

> Can you post the photo you're trying to send? I'm not sure if I can replicate it since I don't have a Windows machine, but I'll try my best.

**Comment by ryanmcgrath** [comment]
Closing due to 4~ years of no activity.
