### ISSUE TITLE
"add_list_member" with "list_id" parameter results in "twython.exceptions.TwythonError: Twitter API returned a 404 (Not Found), Sorry, that page does not exist."

### ISSUE THREAD

**Issue by vickylaixy** [ryanmcgrath/twython#436]
Hi all, just thought I'd point out something that might be a bug. Here's the relevant code:

```python
from queue import Queue

from twython import Twython
from twython import TwythonStreamer

consumer_key = 'xxx'
consumer_secret = 'xxx'
token = 'xxx'
token_secret = 'xxx'
twitter = Twython(consumer_key, consumer_secret, token, token_secret)

def process_tweets(tweets_queue):
    while True:
        tweet = tweets_queue.get()
        twitter.add_list_member(list_id=MY_LIST_ID, user_id=tweet['user']['id'])
        print(tweet['text'].encode('ascii','ignore'))
```

This produces:
```
Traceback (most recent call last):
  File "tweet_stream.py", line 60, in <module>
    process_tweets(tweet_queue)
  File "tweet_stream.py", line 52, in process_tweets
    twitter.add_list_member(list_id=MY_LIST_ID, user_id=tweet['user']['id'])
  File "C:\...\Anaconda3\lib\site-packages\twython\endpoints.py", line 794, in add_list_member
    return self.post('lists/members/create', params=params)
  File "C:\...\Anaconda3\lib\site-packages\twython\api.py", line 268, in post
    return self.request(endpoint, 'POST', params=params, version=version)
  File "C:\...\Anaconda3\lib\site-packages\twython\api.py", line 258, in request
    api_call=url)
  File "C:\...\Anaconda3\lib\site-packages\twython\api.py", line 194, in _request
    retry_after=response.headers.get('X-Rate-Limit-Reset'))
twython.exceptions.TwythonError: Twitter API returned a 404 (Not Found), Sorry, that page does not exist.
```

I noticed a similar issue opened in 2015. Possibly a regression?

**Comment by michaelhelmick** [comment]
Is `MY_LIST_ID` a valid list id?

Please see https://dev.twitter.com/rest/reference/post/lists/members/create for the API documentation.

**Comment by vickylaixy** [comment]
Yes, it's valid.

**Comment by michaelhelmick** [comment]
Can you post the list id?

**Comment by michaelhelmick** [comment]
Or could you try using the list `slug` instead of `list_id`?

**Comment by curiousbrandon** [comment]
This worked for me

`twitter.add_list_member(slug=listname, owner_screen_name=username, screen_name=tweet['user']['screen_name'])`
