### ISSUE TITLE
Cannot import on Windows

### ISSUE THREAD

**Issue by mathurin68** [ryanmcgrath/twython#440]
I'm on Windows 7, python 2.7.13 -

I tried installing from pip and easy_install and setup.py and I can't get it to find Twython.  I can pip install other modules and import them just fine. 

.. appreciate any thoughts, thanks!

>>> import Twython

Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    import Twython
ImportError: No module named Twython
>>> from Twython import twython

Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    from Twython import twython
ImportError: No module named Twython
>>> import simplejson
>>> import twython

Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    import twython
  File "twython.py", line 4, in <module>
    from twython import Twython
ImportError: cannot import name Twython
>>>

**Comment by mathurin68** [comment]
Weird I don't know if cygwin had anything to do with it but I removed cygwin and windows python, reinstalled python and it seems to work fine.
