### ISSUE TITLE
Raspbian: Unable to import or install twython

### ISSUE THREAD

**Issue by slowcodeDK** [ryanmcgrath/twython#545]
I see others also face similar issues.

On my Raspbian, when I write `from twython import Twython` it just says `from: can't read /var/mail/twython`

In Add/remove software I have "Pure Python3 wrapper for the Twitter API" discription:"python3-twython-3.7.0-1"
and 
"Pure Python wrapper for the Twitter API"
I have tried removing them also and then installing new versions, but they won't install.
I have also updated setuptools.

I have tried pip install twython, but it just gives:

```
    root@raspberrypi:/home/pi# pip install twython
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    Requirement already satisfied: twython in /usr/lib/python2.7/dist-packages (3.7.0)
```
But newest version is 3.9.0 or 1 !?

I also tried:

```
    root@raspberrypi:/home/pi# apt-get install python3-twython
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    python3-twython is already the newest version (3.7.0-1).
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I have also tried:

```
 root@raspberrypi:/home/pi# pip install twython==3.9.0
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    Collecting twython==3.9.0
      Using cached https://files.pythonhosted.org/packages/d7/52/90dad657b976da7bfe0c2728d3c562dce516a05992c29ce12a256d456bba/twython-3.9.0.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-H1jomK/twython/setup.py", line 33, in <module>
            long_description=open('README.md', encoding='utf-8').read() + '\n\n' +open('HISTORY.md', encoding='utf-8').read(),
        TypeError: 'encoding' is an invalid keyword argument for this function
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-H1jomK/twython/
```
Also if I import the source files and try to run the setup:

```
root@raspberrypi:/home/pi/twython# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    long_description=open('README.md', encoding='utf-8').read() + '\n\n' +open('HISTORY.md', encoding='utf-8').read(),
TypeError: 'encoding' is an invalid keyword argument for this function

```

I tried without root also.

**Comment by ryanmcgrath** [comment]
Twython's a pure Python package, so... it should really just work. Can you share your script or how you're trying to run stuff?

**Comment by slowcodeDK** [comment]
I am so sorry. I forgot to start python.

**Comment by slowcodeDK** [comment]
Sorry for wasting your life with this.

**Comment by ryanmcgrath** [comment]
Ha! No worries, it happens. Not a waste, someone else will read this and find it useful. :)

Closing now~
